version: '3'
services:
    messaging:
        build: './rabbitmq'
    mysql:
        image: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: changeme
    front_end:
        build: ./front_end
        ports:
            - 5000:5000
    hello:
        build: './Backend/Hello'

    recieve:
        build: './Backend/Receive'
