version: '3'
services:
    messaging1:
        hostname: messaging1
        build: './rabbitmq'
        ports:
          - "5672:5672"
          - "15672:15672"
        environment:
            - ERLANG_COOKIE=abcdefg  
    messaging2:
        hostname: messaging2
        build: './rabbitmq'
        ports:
          - "5673:5672"
          - "15673:15672"
        links:
            - messaging1
        environment:
            - ERLANG_COOKIE=abcdefg
            - CLUSTER_WITH=messaging1
            - ENABLE_RAM=true    
    messaging3:
        hostname: messaging1
        build: './rabbitmq'
        ports:
           - "5674:5672"
          
        links:
           - messaging1
           - messaging2
        environment:
           - ERLANG_COOKIE=abcdefg
    
    mysql:
        image: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_DATABASE: myDB
        ports:
          - "3308:3306"
        volumes:
         - ./database/myvol:/var/lib/mysql
    admin:    
        image: adminer    
        ports:      
         - "8080:8080"
    front_end:
        build: ./front_end
        ports:
            - 5000:5000
   
    recieveregis:
        build: './Backend/RegisAuth'

    recieveauth:
        build: './Backend/loginAuth'

    receiveregis: 
        build: './Backend/ReceiveRegistration'

    sendregis:
        build: './Backend/SendRegistration'

    receivelogin:
        build: './Backend/ReceiveLogin'

    sendlogin:
        build: './Backend/SendLogin'
